eclipse-ee4j/glassfish-hk2

bom/pom.xml, pom.xml
=> Change gpg-sign phase to allow hk2 to build

maven-plugins/pom.xml
=> Resolved pom error

hk2-api/src/main/java/org/glassfish/hk2/api/ClassAnalyzer.java, hk2-api/src/main/java/org/glassfish/hk2/api/InheritableThread.java, hk2-api/src/main/java/org/glassfish/hk2/api/Populator.java, hk2-api/src/main/java/org/glassfish/hk2/api/ServiceLocator.java, hk2-api/src/main/java/org/glassfish/hk2/utilities/AbstractActiveDescriptor.java, hk2-api/src/main/java/org/glassfish/hk2/utilities/DescriptorBuilder.java, hk2-api/src/main/java/org/glassfish/hk2/utilities/DuplicatePostProcessorMode.java, hk2-api/src/main/java/org/glassfish/hk2/utilities/GreedyResolver.java, hk2-api/src/main/java/org/glassfish/hk2/utilities/ImmediateScopeModule.java, hk2-api/src/main/java/org/glassfish/hk2/utilities/PerThreadScopeModule.java, hk2-api/src/main/java/org/glassfish/hk2/utilities/ServiceLocatorUtilities.java, hk2-configuration/hk2-integration/src/main/java/org/glassfish/hk2/configuration/api/ChildIterable.java, hk2-configuration/hk2-integration/src/main/java/org/glassfish/hk2/configuration/internal/BeanUtilities.java, hk2-configuration/persistence/property-file/src/main/java/org/glassfish/hk2/configuration/persistence/properties/PropertyFileHandle.java, hk2-configuration/persistence/property-file/src/main/java/org/glassfish/hk2/configuration/persistence/properties/PropertyFileService.java, hk2-extras/src/main/java/org/glassfish/hk2/extras/operation/OperationContext.java, hk2-locator/src/main/java/org/jvnet/hk2/internal/ConstantActiveDescriptor.java, hk2-locator/src/main/java/org/jvnet/hk2/internal/Creator.java, hk2-runlevel/src/main/java/org/glassfish/hk2/runlevel/RunLevelServiceUtilities.java, hk2-utils/src/main/java/org/glassfish/hk2/utilities/general/internal/MessageInterpolatorImpl.java
=> Resolve javadoc warnings

.gitignore
=> Added .gitignore file to ignore IDE configuration and maven output

maven-plugins/consolidatedbundle-maven-plugin/pom.xml, maven-plugins/hk2-inhabitant-generator/pom.xml, maven-plugins/osgiversion-maven-plugin/pom.xml, maven-plugins/pom.xml, pom.xml
=> Unified version numbers for all modules and maven plugins

pom.xml
=> Moved sign to release profile

hk2-extras/src/main/java/org/glassfish/hk2/extras/operation/OperationHandle.java, hk2-extras/src/main/java/org/glassfish/hk2/extras/operation/internal/OperationHandleImpl.java, hk2-extras/src/test/java/org/glassfish/hk2/tests/locator/messaging/operation/MessagingOperationTest.java, hk2-extras/src/test/java/org/glassfish/hk2/tests/operation/basic/OperationsTest.java, hk2-extras/src/test/java/org/glassfish/hk2/tests/operation/basic/SimpleSingleton.java, hk2-extras/src/test/java/org/glassfish/hk2/tests/operation/shutdown/OperationShutdownTest.java, hk2-extras/src/test/java/org/glassfish/hk2/tests/proxiableshared/ReqContext.java, pom.xml
=> OperationHandle now extends Closable so it can be used with try-with-resources

bom/pom.xml, class-model/pom.xml, examples/configuration/webserver/pom.xml, examples/configuration/xml/pom.xml, hk2-configuration/hk2-integration/pom.xml, hk2-configuration/persistence/hk2-xml/hk2-json/pom.xml, hk2-configuration/persistence/hk2-xml/main/pom.xml, hk2-configuration/persistence/hk2-xml/schema/pom.xml, hk2-core/pom.xml, hk2-extras/pom.xml, hk2-locator/pom.xml, hk2-metadata-generator/main/pom.xml, hk2-metadata-generator/test1/pom.xml, hk2-runlevel/pom.xml, hk2-testing/hk2-locator-extras/pom.xml, hk2-testing/hk2-runlevel-extras/pom.xml, hk2-testing/jersey/jersey-guice/form-param/pom.xml, hk2-utils/pom.xml, pom.xml
=> Update to use jakarta dependencies

hk2-api/src/main/java/org/glassfish/hk2/api/ServiceHandle.java, hk2-api/src/main/java/org/glassfish/hk2/utilities/BuilderHelper.java, hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceHandleImpl.java, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/classanalysis/ClassAnalysisTest.java, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/lifecycle/LifecycleTest.java, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/errorservice1/ErrorService1Test.java, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/proxiable2/ProxiableTest.java
=> ServiceHandle now extends Closable for use with try-with-resources

guice-bridge/src/main/java/org/jvnet/hk2/guice/bridge/internal/HK2ToGuiceTypeListenerImpl.java
=> Guice bridge also checks for @BindingAnnotation

hk2-core/src/main/java/com/sun/enterprise/module/HK2Module.java, hk2-core/src/main/java/com/sun/enterprise/module/ImportPolicy.java, hk2-core/src/main/java/com/sun/enterprise/module/LifecyclePolicy.java, hk2-core/src/main/java/com/sun/enterprise/module/ModuleChangeListener.java, hk2-core/src/main/java/com/sun/enterprise/module/ModuleLifecycleListener.java, hk2-core/src/main/java/com/sun/enterprise/module/ModulesRegistry.java, hk2-core/src/main/java/com/sun/enterprise/module/common_impl/AbstractFactory.java, hk2-core/src/main/java/com/sun/enterprise/module/common_impl/AbstractModulesRegistryImpl.java, hk2-core/src/main/java/com/sun/enterprise/module/impl/ModuleClassLoader.java, hk2-core/src/main/java/com/sun/enterprise/module/impl/ModuleImpl.java, hk2-core/src/main/java/com/sun/enterprise/module/impl/ModulesRegistryImpl.java, hk2-core/src/main/java/com/sun/enterprise/module/impl/Utils.java, hk2-core/src/main/java/com/sun/enterprise/module/single/ClassPathBasedModulesRegistry.java, hk2-core/src/main/java/com/sun/enterprise/module/single/ProxyModule.java, hk2-core/src/main/java/com/sun/enterprise/module/single/SingleModulesRegistry.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/AbstractOSGiModulesRegistryImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiModuleImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiModulesRegistryImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiObrModuleImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiObrModulesRegistryImpl.java
This is for JDK9+ to avoid ambiguities with java.lang.Module
=> Renamed Module to HK2Module

.gitignore, external/asm-all/pom.xml, maven-plugins/pom.xml, pom.xml
Signed-off-by: smillidge <steve.millidge@payara.fish>
=> Shade all asm jars after the 6.0 split

class-model/pom.xml, external/jsr330/pom.xml, hk2-configuration/persistence/hk2-xml/main/pom.xml, hk2-configuration/persistence/hk2-xml/test1/src/test/java/org/glassfish/hk2/xml/test/interop/InteropTest.java, hk2-utils/pom.xml, osgi/adapter-tests/osgi-adapter-test/src/test/java/org/jvnet/hk2/osgiadapter/OSGiTest.java, osgi/adapter-tests/osgi-adapter-test/src/test/java/org/jvnet/hk2/osgiadapter/ServiceLocatorHk2MainTest.java, pom.xml
Errors were due to misnamed dependencies and a change in jsonp
=> Fixes for build errors

.gitignore, README.md, hk2-configuration/persistence/hk2-xml/hk2-pbuf/pom.xml, hk2-configuration/persistence/hk2-xml/hk2-pbuf/src/main/java/org/glassfish/hk2/pbuf/internal/PBufParser.java, hk2-configuration/persistence/hk2-xml/hk2-pbuf/src/test/java/org/glassfish/hk2/pbuf/test/basic/PBufParserTest.java, pom.xml
Reverts eclipse-ee4j/glassfish-hk2#421
=> Revert "Update pbuf to remove useless and dangerous cache"

.gitignore, hk2-configuration/persistence/hk2-xml/hk2-pbuf/pom.xml, hk2-configuration/persistence/hk2-xml/hk2-pbuf/src/main/java/org/glassfish/hk2/pbuf/internal/PBufParser.java, hk2-configuration/persistence/hk2-xml/hk2-pbuf/src/test/java/org/glassfish/hk2/pbuf/test/basic/PBufParserTest.java, pom.xml
Fixes #420 
Signed-off-by: John Wells <jwells131313@gmail.com>
=> Update pbuf to remove useless and dangerous cache

osgi/adapter-tests/osgi-adapter-test/pom.xml, osgi/adapter-tests/osgi-adapter-test/src/test/java/org/jvnet/hk2/osgiadapter/OSGiTest.java, osgi/adapter-tests/osgi-adapter-test/src/test/java/org/jvnet/hk2/osgiadapter/ServiceLocatorHk2MainTest.java, pom.xml
Fix and cleanup OSGi adapter tests
=> Fix OSGi adapter-tests

pom.xml
=> License and Notice files are now included in the META-INF directory

class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/ParsingContext.java
Setting location in builder causes NPE.
=> Fix NullPointerException / typo in ParsingContext

hk2-configuration/persistence/hk2-xml/hk2-pbuf/src/main/java/org/glassfish/hk2/pbuf/api/PBufUtilities.java, hk2-configuration/persistence/hk2-xml/hk2-pbuf/src/main/java/org/glassfish/hk2/pbuf/internal/PBufParser.java, hk2-configuration/persistence/hk2-xml/hk2-pbuf/src/test/java/org/glassfish/hk2/pbuf/test/basic/PBufParserTest.java, hk2-utils/pom.xml, pom.xml
Another go at merging in the EE4J_8 branch
=> Merge EE4J branch into master

hk2-configuration/hk2-integration/src/main/java/org/glassfish/hk2/configuration/internal/ConfiguredByContext.java
Fixes #412
Signed-off-by: Sven Diedrichsen <sdiedrichsen@yahoo.de>
=> (#412) ConcurrentModificationException on shutdown

examples/pom.xml, external/asm-all/pom.xml, hk2-metadata-generator/pom.xml, hk2-testing/ant/pom.xml, hk2-testing/hk2-mockito/pom.xml, hk2-testing/hk2-runlevel-extras/pom.xml, hk2-testing/hk2-testng/pom.xml, hk2-testing/interceptor-events/pom.xml, hk2-testing/jersey/jersey-guice/form-param/pom.xml, hk2-utils/pom.xml, javadocs/pom.xml, maven-plugins/osgiversion-maven-plugin/pom.xml, maven-plugins/pom.xml, osgi/adapter-tests/osgi-adapter-test/pom.xml, pom.xml
With required pom changes for new options
=> Update maven-jar-plugin to 3.1.1

Jenkinsfile, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/multithreaded1/MultiThreaded1Test.java
fixes #452 
Signed-off-by: smillidge <steve.millidge@payara.fish>
=> Add Jenkinsfile for new build pipeline. Copied from hk2-extra

pom.xml
Includes fix for CVE-2018-10237
=> Upgrade guice to version 4.2.1

hk2-utils/src/main/java/org/glassfish/hk2/utilities/general/Hk2ThreadLocal.java
Fixes #460.
This change updates Hk2ThreadLocal to use a ConcurrentHashMap.
Signed-off-by: Bryan Atsatt <bryan.atsatt@oracle.com>
=> Bug 460 - Reduce Hk2ThreadLocal lock contention.

hk2-core/src/main/java/com/sun/enterprise/module/common_impl/AbstractModulesRegistryImpl.java
- also some formatting and reorganized imports
- exception with a message is better than NPE
Signed-off-by: David Matejcek <dmatej@seznam.cz>
=> Fixed #464 Better exception if the DynamicConfigurationService was not found

hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/children/ChildServiceLocatorTest.java
Signed-off-by: Jan Supol <jan.supol@oracle.com>
=> Fix child service locator shutdown

osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiModuleImpl.java
When starting multiple OSGi modules in parallel (like RunLevel service tends to do), Apache Felix may run into lock race condition that is demonstrated by throwing
```
org.osgi.framework.BundleException: Unable to acquire global lock for resolve.
```
The operation should be retried in such case.
=> Retry bundle start on Felix' global lock race condition

hk2-metadata-generator/main/src/main/java/org/glassfish/hk2/stub/generator/StubProcessor.java
Add @SuppressWarnings({"unchecked","rawtypes"}) to code generated from StubProcessor.
=> @SuppressWarnings on StubProcessor generated code

Jenkinsfile
As indicated in https://bugs.eclipse.org/bugs/show_bug.cgi?id=551841
=> Updated Jenkinsfile so it will run on new Eclipse CI

pom.xml
=> Upgrade asm to version 7.3.1

class-model/pom.xml, external/aopalliance/pom.xml, guice-bridge/pom.xml, hk2-api/pom.xml, hk2-configuration/hk2-integration/pom.xml, hk2-configuration/manager/pom.xml, hk2-core/pom.xml, hk2-extras/pom.xml, hk2-jmx/pom.xml, hk2-locator/pom.xml, hk2-runlevel/pom.xml, hk2-utils/pom.xml, maven-plugins/consolidatedbundle-maven-plugin/pom.xml, maven-plugins/hk2-inhabitant-generator/pom.xml, maven-plugins/osgiversion-maven-plugin/pom.xml, spring-bridge/pom.xml
=> Added automatic-module-name into manifests

class-model/pom.xml, maven-plugins/consolidatedbundle-maven-plugin/pom.xml, pom.xml
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
=> Update java versions and master version

bom/pom.xml, javadocs/pom.xml
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
=> Set HK2 Bom version to 3.0.0-SNAPSHOT

bom/pom.xml
Signed-off-by: smillidge <steve.millidge@payara.fish>
=> Update to latest Eclipse parent pom

hk2-testing/jersey/jersey-guice/pom.xml, pom.xml
=> Upgrade grizzly and jersey; reenable jersey tests

hk2-api/src/main/java/org/glassfish/hk2/api/ServiceLocator.java, hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/servicelocatorutilities/ServiceLocatorUtilitiesTest.java
=> Add a method to check if the service locator has been shutdown

bom/pom.xml
=> Add used properties into bom

hk2-api/src/main/java/org/glassfish/hk2/utilities/ClasspathDescriptorFileFinder.java
The new constructor in ClasspathDescriptorFileFinder would be handy in case the locator directory is not META-INF/hk2-locator. Moreover, the new constructor does not contain the locator file names as it will scan all the files automatically in the given locator directory, meaning by using this constructor, all files in the given directory are assumed to be HK2 descriptor files.
For instance, I tried to use inhabitants-generator to generate the service locator files into the war, and the location is indeed not META-INF/hk2-locator but hk2-locator. In this case, the new constructor would be used
=> A new constructor is added to ClasspathDescriptorFileFinder

examples/security-lockdown/runner/src/test/java/org/glassfish/securitylockdown/test/SecurityLockdownTest.java, hk2-api/src/main/java/org/glassfish/hk2/api/DuplicateServiceException.java, hk2-api/src/main/java/org/glassfish/hk2/api/UnsatisfiedDependencyException.java, hk2-extras/src/main/java/org/glassfish/hk2/extras/provides/InjectUtils.java, hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java, hk2-locator/src/main/java/org/jvnet/hk2/internal/ThreeThirtyResolver.java, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/errorservice/ErrorServiceTest.java, hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/validating/ValidatingTest.java
=> Display servicelocator name in exception

pom.xml
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
=> Update Jakarta APIs to final and update to latest impls

hk2-api/src/main/java/org/glassfish/hk2/utilities/ClasspathDescriptorFileFinder.java
=> Unable to load descriptors in Windows environment

pom.xml
=> Wrong plugin version in pom.xml

bom/pom.xml, pom.xml
Update dependencies to final versions.
=> Update dependencies in pom.xml

class-model/osgi.bundle, hk2-api/osgi.bundle, hk2-utils/osgi.bundle, pom.xml
Also all osgi.bundle files now use correct commenting system.
=> Upgrade OSGi felix plugins

bom/pom.xml, pom.xml
Do not merge till #546 is merged
=> Update ASM to 9.1

hk2-configuration/persistence/hk2-xml/main/src/main/java/org/glassfish/hk2/xml/internal/JAUtilities.java, hk2-locator/src/test/resources/policy.txt, pom.xml
Signed-off-by: jansupol <jan.supol@oracle.com>
=> Prevent Illegal reflective access in JAUtilities

Jenkinsfile
To use Jakarta EE 10, like in
- #624
=> Switch JDK used on Jenkins

Jenkinsfile
=> Switch JDK used in build from 11 to 17

.mvn/maven.config, pom.xml
=> Update dependencies for new servlet 6 to work

class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/Parser.java
- the log message didn't provide any useful information, just "I do something"
- was spamming glassfish logs
=> Imports, generics and reduced log level for "Visiting univisited references"

class-model/pom.xml, pom.xml
Updates `osgi.enterprise` to 7.0.0.
=> Update OSGi Enterprise to 7.0.0

class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/EnumTypeImpl.java, hk2-api/src/main/java/org/glassfish/hk2/internal/ImmediateHelper.java, hk2-configuration/persistence/hk2-xml/main/src/main/java/org/glassfish/hk2/xml/tools/Hk2XmlGenerator.java, hk2-extras/src/main/java/org/glassfish/hk2/extras/hk2bridge/internal/Hk2BridgeImpl.java, hk2-extras/src/main/java/org/glassfish/hk2/extras/operation/OperationContext.java, hk2-extras/src/main/java/org/glassfish/hk2/extras/provides/ProvidesDescriptor.java, hk2-extras/src/main/java/org/glassfish/hk2/extras/provides/ProvidesListener.java, hk2-utils/src/main/java/org/glassfish/hk2/utilities/general/internal/WeakHashLRUImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/AbstractOSGiModulesRegistryImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/ModuleDefinitionCacheSingleton.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiFactoryImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiModuleImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiModulesRegistryImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiObrModuleImpl.java, osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/ObrHandler.java
I have realized that there are still some _synchronized_ blocks in _master_ that didn't exist in _2.x-maintenance_ and I am covering them in this new commit.
=> Reentrantlock additions of master

hk2-core/src/main/java/com/sun/enterprise/module/single/ManifestProxy.java
=> Added InaccessibleObjectException to the list of caught exceptions

hk2-extras/pom.xml
So that it's possible to initialize the default topic handler  and use other features
=> Export non-internal pacakges from hk2-extras

hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java
=> Revert: Search for scope first in parent locator. PR #1166

pom.xml
=> Downgrade components to Jakarta EE 10 and Java level 11 for 3.1.x
