maven-plugins/hk2-inhabitant-generator/pom.xml
maven-plugins/hk2-inhabitant-generator/src/test/java/org/jvnet/hk2/generator/tests/InhabitantsGeneratorTest.java
pom.xml

Removed references to non-existent classes and made compiled output into
what the test expects.

Fix for hk2-inhabitant-generator so it passes all tests.

---

.gitignore
examples/custom-resolver/pom.xml
examples/operations/pom.xml
external/jsr330/pom.xml
guice-bridge/pom.xml
hk2-api/pom.xml
hk2-extras/pom.xml
hk2-jmx/pom.xml
hk2-locator/pom.xml
hk2-metadata-generator/main/pom.xml
hk2-metadata-generator/test1/pom.xml
hk2-testing/hk2-junitrunner/pom.xml
hk2-testing/hk2-locator-extras/pom.xml
hk2-testing/hk2-locator-no-proxies/pom.xml
hk2-testing/hk2-locator-no-proxies2/pom.xml
hk2-testing/hk2-mockito/pom.xml
hk2-testing/hk2-runlevel-extras/pom.xml
hk2-testing/hk2-testng/pom.xml
hk2-testing/interceptor-events/pom.xml
hk2-testing/jersey/jersey-guice/form-param/pom.xml
hk2-utils/pom.xml
maven-plugins/hk2-inhabitant-generator/pom.xml
osgi/adapter-tests/no-hk2-bundle/pom.xml
osgi/adapter-tests/osgi-adapter-test/pom.xml
spring-bridge/pom.xml

fix broken renaming of org.glassfish.hk2.external:javax.inject to org.glassfish.hk2.external:jakarta.inject

Fix javax inject dependencies

---

external/asm-all/pom.xml

Otherwise it gets corrupted and other tools cannot handle it properly
(see for example https://youtrack.jetbrains.com/issue/KT-23025)
Also, here's the output of `javap` on the transformed `module-info.class` file:
```
Classfile /Users/udalov/hk2/external/asm-all/module-info.class
Last modified Apr 18, 2018; size 90 bytes
MD5 checksum e5c89b529cf24511d1d0cb836c8bc178
Error: invalid index #4
Error: invalid index #5
open module ???@???
minor version: 0
major version: 53
flags: (0x8000) ACC_MODULE
this_class: #2                          // "module-info"
super_class: #0
interfaces: 0, fields: 0, methods: 0, attributes: 1
Constant pool:
#1 = Utf8               module-info
#2 = Class              #1              // "module-info"
#3 = Utf8               Module
{
}
Module:
Error: invalid index #4 …
```

Do not shade module-info.class from asm-all

---

pom.xml

These two deps are mentioned in the dep management section
but are never actually used by any module:
* osgi_R4_core
* com.springsource.org.junit
Signed-off-by: Mat Booth <mat.booth@redhat.com>

Removed unused dependencies from pom.xml

---

hk2-configuration/persistence/hk2-xml/main/pom.xml

- fixed dependency on system language
- caused tests failing if the default user language was set to other than english

Tests in hk2-xml does not depend on system locale

---

CHANGELOG
hk2-locator/pom.xml
hk2-locator/src/main/java/org/jvnet/hk2/internal/OptionalActiveDescriptor.java
hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/factory/DateInjectee.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/factory/FactoryTest.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/InjectedManyTimes.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/NullWidgetFactory.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/OptionalModule.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/Widget.java

This includes all the features requested in #457 , allowing for injection of `Optional<Object>` instead of using the `@Optional` annotation.

Add support for java.util.Optional

---

hk2-api/src/main/java/org/glassfish/hk2/utilities/IgnoringErrorService.java
hk2-core/src/main/java/com/sun/enterprise/module/single/StaticModulesRegistry.java
hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/classanalysis/ConfigurablyBadClassAnalyzer.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/classanalysis/NegativeClassAnalysisModule.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/classanalysis/NegativeClassAnalysisTest.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/errorservice1/ErrorService1Test.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/factory/BadlyNamedFactory.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/factory/NegativeFactoryTest.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/servicelocatorutilities/ServiceLocatorUtilitiesTest.java
hk2-testing/hk2-testng/src/main/java/org/jvnet/testing/hk2testng/HK2TestListenerAdapter.java

- originally the HK2 ignored all errors, so when the DynamicConfigurationService
was not accessible because of classloading issues (on JDK11), it ended up
with NPE without any usabe cause
- now by default throws out any "reify" exception that can occur
until it is configured to use another ErrorService implementation
- original behavior can be reached by configuring the IgnoringErrorService,
but only after successful serviceloader initialization (StaticModulesRegistry
now does it)
- initialization is successful and the service is configured
OR you catch an exception, but you should not get unconfigured failing locator.
- tests were reviewed and fixed, because sometimes they tested states that
could not be reached without swallowing exceptions.
- one more test for the new implementation …

Issue #475 Changed default error handling of HK2

---

hk2-runlevel/src/main/java/org/glassfish/hk2/runlevel/internal/AsyncRunLevelContext.java

This allows the associated thread to be distinguished.
Fixes #29

Give the Timer in AsyncRunLevelContext a name.

---

hk2-api/src/main/java/org/glassfish/hk2/utilities/IgnoringErrorService.java
hk2-core/src/main/java/com/sun/enterprise/module/single/StaticModulesRegistry.java
hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/classanalysis/ConfigurablyBadClassAnalyzer.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/classanalysis/NegativeClassAnalysisModule.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/classanalysis/NegativeClassAnalysisTest.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/errorservice1/ErrorService1Test.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/factory/BadlyNamedFactory.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/negative/factory/NegativeFactoryTest.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/servicelocatorutilities/ServiceLocatorUtilitiesTest.java
hk2-testing/hk2-junitrunner/src/main/java/org/jvnet/hk2/testing/junit/HK2JunitRunner.java
hk2-testing/hk2-junitrunner/src/main/java/org/jvnet/hk2/testing/junit/HK2Runner.java
hk2-testing/hk2-junitrunner/src/main/java/org/jvnet/hk2/testing/junit/internal/TestServiceLocator.java
hk2-testing/hk2-junitrunner/src/test/java/org/jvnet/hk2/testing/test/JunitRunnerTest.java
hk2-testing/hk2-mockito/src/main/java/org/jvnet/testing/hk2mockito/HK2MockitoInjectionResolver.java
hk2-testing/hk2-mockito/src/main/java/org/jvnet/testing/hk2mockito/MC.java
hk2-testing/hk2-mockito/src/main/java/org/jvnet/testing/hk2mockito/internal/MockitoService.java
hk2-testing/hk2-mockito/src/test/java/org/jvnet/testing/hk2mockito/IndirectCollaboratorMockInjectionTest.java
hk2-testing/hk2-mockito/src/test/java/org/jvnet/testing/hk2mockito/MultipleInjectionTest.java
hk2-testing/hk2-mockito/src/test/java/org/jvnet/testing/hk2mockito/fixture/service/DeepService.java
hk2-testing/hk2-mockito/src/test/java/org/jvnet/testing/hk2mockito/fixture/service/MultipleConstructorInjectionService.java
hk2-testing/hk2-testng/src/main/java/org/jvnet/testing/hk2testng/HK2TestListenerAdapter.java
osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiModuleImpl.java

This PR adds support for testing nested dependencies using `@SUT`, `@MC` and `@SC`.
If Service `A` depends on `B` which in turn depends on `C`. Then this PR allows you to test `A` using `B` while mocking `C`. This is necessary for doing integration testing where a low-level system access service needs to be mocked only.
So now we can declare `@SUT A a` and `@MC C c` which instantiates the intermediate service `B`.
Example:
`org/jvnet/testing/hk2mockito/IndirectCollaboratorMockInjectionTest.java`
At the same time it provides a `JUnitRunner` interface to avoid having to use inheritance. It provides a way to write JUnit tests that conform with the way tests are written in JUnit. It loses the more fine-grained control that comes with inheritance.

Nested dependencies testing

---

class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/ExtensibleType.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/FieldModel.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/Parameter.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/ParameterizedInterfaceModel.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/ParameterizedType.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/ExtensibleTypeImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/FieldModelImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/FieldSignatureVisitorImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/MethodSignatureVisitorImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/ModelClassVisitor.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/ParameterImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/ParameterizedInterfaceModelImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/ParameterizedTypeImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/SignatureVisitorImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/TypeBuilder.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/TypeImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/TypesCtr.java
class-model/src/test/java/org/glassfish/hk2/classmodel/reflect/test/method/MethodTest.java

This PR improving the parsing of Java Generic type and Formal type signature defined on the classes and fields.
Model class representing the ParameterizedType:
https://github.com/eclipse-ee4j/glassfish-hk2/blob/7c8451eea3d4d6f71fe0469b6906bf07d9a31057/class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/ParameterizedType.java
To parse the parameterized type defined on fields:
https://github.com/eclipse-ee4j/glassfish-hk2/blob/7c8451eea3d4d6f71fe0469b6906bf07d9a31057/class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/FieldSignatureVisitorImpl.java

Generic type parser for Class and fields

---

guice-bridge/src/test/java/org/jvnet/hk2/guice/bridge/test/GuiceBridgeTest.java
guice-bridge/src/test/java/org/jvnet/hk2/guice/bridge/test/GuiceBridgeTestModule.java
guice-bridge/src/test/java/org/jvnet/hk2/guice/bridge/test/GuiceService5.java
guice-bridge/src/test/java/org/jvnet/hk2/guice/bridge/test/HK2Service5.java
hk2-locator/src/main/java/org/jvnet/hk2/internal/OptionalActiveDescriptor.java
hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/NamedOptionalInjection.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/NamedOptionalTest.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/NestedOptionalInjection.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/NestedOptionalTest.java

Add tests and fixes for:
1. OptionalActiveDescriptor fails to inject @Named optional values, because (name) qualifiers are not propagated for the retrieval of the wrapped value. As a consequence any bound instance (unnamed, with same name, or other name) may be injected.
This is a treacherous bug, in particular when injecting configuration parameters and migrating from previous versions.
2. Trying to inject Optional<Optional<String>> one might expect the following:
- Binding a literal string results to Optional<Optional<String>>, but actaally Optional<Optional.empty> is injected
- Binding Optional<Optional<String> results to Optional<Optional<String>, but actually Optional<Optional<Optional<String>>> is injected    
Furthermore, one might expect that more specific bindings take precedence …

Fix optional injection bugs

---

class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/TypesCtr.java

This is a fix to avoid ClassCastException by filtering the TypeProxy instance with the storage type.
Related PRs:
https://github.com/payara/patched-src-hk2/pull/17

FISH-743 Fetch TypeProxy holder by filtering with type

---

pom.xml

Sorry for this.. I had locally tested with 3.22.0-GA but updated it to 3.27.0-GA in the previous PR #539

Downgrade javaassist to 3.22.0-GA

---

pom.xml

Once again the release script updated plugin versions to SNAPSHOT. See #537

Update plugin version for source and javadoc plugins

---

CHANGELOG
hk2-locator/pom.xml
hk2-locator/src/test/resources/policy.txt
pom.xml

Continuation of PR #542
Revert hk2-locator/pom.xml to original
Resolve AccessControlException thrown with javassist-3.27.0-GA
```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "createSecurityManager")
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "defineClass")
```
These exceptions are visible only when passing the -Djava.security.debug=access flag.

Build jdk15

---

class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/FieldModelImpl.java
class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/ParameterImpl.java
class-model/src/test/java/org/glassfish/hk2/classmodel/reflect/test/ClassModelTestsUtils.java
class-model/src/test/java/org/glassfish/hk2/classmodel/reflect/test/ModelTest.java
class-model/src/test/java/org/glassfish/hk2/classmodel/reflect/test/parameterized/GenericRouteBuilder.java
class-model/src/test/java/org/glassfish/hk2/classmodel/reflect/test/parameterized/PathRouteBuilder.java
class-model/src/test/java/org/glassfish/hk2/classmodel/reflect/test/parameterized/RouteBuilder.java

Hi there.  While investigating https://github.com/payara/Payara/issues/5119, I discovered that _almost_ all of the TypeProxy references in the class-model are wrapped in null checks.  Two remain that I could find, including one that is a cause of the NullPointerException in OpenAPI I'm working on.
This PR wraps those two TypeProxy references in null checks, and adds a bunch of tests.  I was able to get a good test going for the ParameterImpl change based on the issue above.  If you run these tests against v3.0.1, they will fail.  The FieldImpl change was harder, and I don't have a good example case where TypeProxy would be null in the real world.

Consistent null-checking for TypeProxy

---

maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/internal/AbstractAnnotationVisitorImpl.java
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/internal/AbstractClassVisitorImpl.java
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/internal/AbstractMethodVisitorImpl.java

For proper JDK-17 support there is a need to have ASM9 support otherwise PermittedSubclasses requires ASM9 appears. Please consider this PR to be applied to master.

Upgraded version ASM opsCodes from 7 to 9 

---

hk2-testing/hk2-mockito/pom.xml

Reverts eclipse-ee4j/glassfish-hk2#588
Breaks the code. Mockito needs to be updated manually.

Revert "Bump mockito-core from 2.18.3 to 4.4.0"

---

pom.xml

Insane.
Original PR
- #604 
consistently fails on Jenkins. In test that seems to not use AssertJ.
Cannot reproduce that fail locally.
I've checked every AJ version in https://ci.eclipse.org/glassfish/job/hk2/job/pr604/ - and not a single one failed.
This PR - identical with PR-604: https://github.com/eclipse-ee4j/glassfish-hk2/compare/dependabot/maven/org.assertj-assertj-core-3.22.0..pzygielo:assertj passed Jenkins fine.
I've no clues for the reason.
-----
This closes #604.

Bump assertj-core from 3.15.0 to 3.22.0

---

Jenkinsfile
examples/security-lockdown/runner/pom.xml
hk2-api/pom.xml
hk2-configuration/persistence/hk2-xml/integration-test/pom.xml
hk2-configuration/persistence/hk2-xml/main/pom.xml
hk2-configuration/persistence/hk2-xml/schema/pom.xml
hk2-configuration/persistence/hk2-xml/test1/pom.xml
hk2-locator/pom.xml
hk2-metadata-generator/main/pom.xml
hk2-metadata-generator/test1/pom.xml
hk2-runlevel/pom.xml
maven-plugins/hk2-inhabitant-generator/pom.xml
pom.xml

Collect coverage reports with builds on Jenkins

---

hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/children/ChildServiceLocatorTest.java
hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/optional/NestedOptionalTest.java

This will (partially) help with
- #607 
There is a 3.5 release of EasyMock (currently used here) that has TestNG classes included (it's fixed in [3.5.1](https://github.com/easymock/easymock/releases/tag/easymock-3.5.1)), that polluted CP.
HK2 has no TestNG on CP, hence the problem of upgrading from 3.5 up.

Un-mix TestNG Assert from JUnit Tests

---

hk2-api/src/test/java/org/glassfish/hk2/utilities/binding/BindingTest.java

This will (partially) help with
- #607 
`Capture` constructor was removed in EasyMock 4.0:
- easymock/easymock#231

Replace usage of deprecated Ctor

---

pom.xml

Avoid
```
21:55:58  [WARNING] 
21:55:58  [WARNING] Some problems were encountered while building the effective model for org.glassfish.hk2:hk2-di-tck-runner:jar:3.0.4-SNAPSHOT
21:55:58  [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-install-plugin is missing. @ line 93, column 21
21:55:58  [WARNING] 
21:55:58  [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
21:55:58  [WARNING] 
21:55:58  [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
21:55:58  [WARNING] 
```
from modules explicitly using that plugin w/o version.
2.4 is the version configured in current maven.

Explicit version for m-install-p

---

hk2-locator/src/test/java/org/glassfish/hk2/tests/locator/multithreaded1/MultiThreaded1Test.java

It seems this test depends on performance of machine it runs on:
- https://ci.eclipse.org/glassfish/job/hk2/job/PR-643/1/console
- https://ci.eclipse.org/glassfish/job/hk2/job/master/86/console
- https://ci.eclipse.org/glassfish/job/hk2/job/master/89/console
- https://ci.eclipse.org/glassfish/job/hk2/job/master/91/console
Thus I propose to patch it with new timeout value for now.

Extend timeout to 120s

---

pom.xml

Related:
- https://github.com/eclipse-ee4j/glassfish-hk2/pull/714
- https://github.com/eclipse-ee4j/glassfish-hk2/pull/597
It seems initial contribution had this only managed. Upstream used this dependency in `:osgi-adapter-test`, but it was later removed from that module.
`slf4j-simple` does not transit from other dependencies:
```
[INFO] --- maven-dependency-plugin:3.3.0:tree (default-cli) @ osgi-adapter-test ---
[INFO] org.glassfish.hk2:osgi-adapter-test:jar:3.0.4-SNAPSHOT
[INFO] +- org.glassfish.hk2:hk2-utils:jar:3.0.4-SNAPSHOT:compile
[INFO] +- org.glassfish.hk2:hk2-api:jar:3.0.4-SNAPSHOT:compile
[INFO] +- org.glassfish.hk2:hk2-locator:jar:3.0.4-SNAPSHOT:compile
[INFO] +- org.glassfish.hk2:hk2-runlevel:jar:3.0.4-SNAPSHOT:compile
[INFO] +- …
```

Drop management of unused dependency

---

class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/impl/TypeImpl.java
hk2-api/src/main/java/org/glassfish/hk2/internal/InheritableThreadContext.java
hk2-api/src/main/java/org/glassfish/hk2/internal/PerThreadContext.java
hk2-api/src/main/java/org/glassfish/hk2/utilities/CleanerFactory.java
hk2-core/src/main/java/com/sun/enterprise/module/impl/ClassLoaderFacade.java
hk2-core/src/main/java/com/sun/enterprise/module/impl/ClassLoaderProxy.java
hk2-core/src/main/java/com/sun/enterprise/module/impl/ModuleClassLoader.java

In this PR, a few performance optimizations have been done.
- The `finalize` method has been deprecated and removed from FileInputStream, FileOutputStream, Zip Inflator, and  Deflator in JDK 12 which may cause resources are not cleaned and leak.
- File canonicalization cache is disabled by default in JDK 12 which helps in performance optimizations for file name canonicalization. In TypeImpl#addDefiningURI duplicate uri is added so canonicalization is not required.

FISH-6432 Applications Take Longer To Deploy on JDK 17

---

.mvn/maven.config

Fixes 
```
mvn clean install
Unable to parse maven.config file options: Unrecognized option: --activate-profiles staging
```
with Maven 3.9.0+

Using compatible arguments

---

hk2-testing/hk2-junitrunner/pom.xml
javadocs/pom.xml
maven-plugins/consolidatedbundle-maven-plugin/pom.xml
maven-plugins/consolidatedbundle-maven-plugin/src/main/java/com/sun/enterprise/module/maven/HK2GenerateMojo.java
maven-plugins/hk2-inhabitant-generator/pom.xml
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/maven/AbstractInhabitantsGeneratorMojo.java
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/maven/InhabitantsGeneratorMojo.java
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/maven/TestInhabitantsGeneratorMojo.java
maven-plugins/osgiversion-maven-plugin/pom.xml
maven-plugins/osgiversion-maven-plugin/src/main/java/com/sun/enterprise/module/maven/OsgiVersionMojo.java
maven-plugins/osgiversion-maven-plugin/src/main/java/org/glassfish/hk2/maven/Version.java
osgi/adapter/pom.xml
pom.xml
spring-bridge/pom.xml

* Originally reported by @arjantijms 
* deprecated javadocs in maven plugins
* JUnit4 URL changed
* The maven-osgi dependency is dead, we should get rid of it. Now I replaced it's dependencies by latest, seems it is working
* spring module had conflicts on classpath

Fixed issues reported by maven when we tried to deploy a pre-release

---

bom/pom.xml
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/maven/AbstractInhabitantsGeneratorMojo.java
pom.xml

"now" date was injected in generated `META-INF/hk2-locator/default`, and parameter `includeDate` to disable it was ignored because plugin variable was marked final
fixes Reproducible Builds issues found in previous release: https://github.com/jvm-repo-rebuild/reproducible-central/tree/master/content/org/glassfish/hk2

fix Reproducible Builds issues

---

pom.xml

17 needed due to
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project spring-bridge: Compilation failure: Compilation failure: [ERROR] spring-bridge/src/main/java/org/jvnet/hk2/spring/bridge/api/SpringScopeImpl.java:[24,41] cannot access org.springframework.beans.factory.ObjectFactory
[ERROR]   bad class file: org/springframework/spring-beans/6.0.11/spring-beans-6.0.11.jar(/org/springframework/beans/factory/ObjectFactory.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Bump required JDK

---

hk2-core/src/main/java/com/sun/enterprise/module/ModuleMetadata.java
hk2-core/src/main/java/com/sun/enterprise/module/common_impl/ByteArrayInhabitantsDescriptor.java
osgi/adapter/src/main/java/org/jvnet/hk2/osgiadapter/OSGiModuleDefinition.java

In file: OSGiModuleDefinition.java, ByteArrayInhabitantsDescriptor.java and ModuleMetadata.java, some classes explicitly implement serializable but they do not contain any serialVersionUID field. The compiler generates one by default in such scenarios, but the generated id is dependent on compiler implementation and may cause unwanted problems during deserialization.
The primary role of serialVersionUID is to provide version control during deserialization. When we deserialize an object, the JVM checks whether the serialVersionUID of the serialized data matches the serialVersionUID of the class in the current classpath. If they match, the deserialization proceeds without issues. However, if they do not match, programmers encounter InvalidClassException.
As, serialVersionUID servers the …

SerialVersionUID fix for all the classes that implement Serializable

---

hk2-api/src/main/java/org/glassfish/hk2/internal/PerThreadContext.java

The `PerThreadContextWrapper` is never cleaned up because cleaning action hold reference to it and thus he never become phantom reachable and cleaning action will not be invoked automatically.
This closes #949, eclipse-ee4j/jersey#5486 and perhaps eclipse-ee4j/glassfish#24672

Fixes memory leak in per-thread context

---

.gitignore
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/internal/AbstractAnnotationVisitorImpl.java
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/internal/AbstractClassVisitorImpl.java
maven-plugins/hk2-inhabitant-generator/src/main/java/org/jvnet/hk2/generator/internal/AbstractMethodVisitorImpl.java
pom.xml

Upgrading to ASM 9.6, that is supported from JDK 1.5:
```
$ javap -verbose /home/jbescos/Downloads/asm-9.6/org/objectweb/asm/Opcodes.class | grep major
major version: 49
```
Some context: WLS 14.1.2 uses JDK 17

Ugrade ASM to support higher JDK versions

---

hk2-runlevel/src/main/java/org/glassfish/hk2/runlevel/internal/CurrentTaskFuture.java

Fixes a race during bringing the current runlevel of the system down.
`CurrentTaskFuture` may compete before all the tasks it performs have completed (perhaps due to spurious wakeup or reordering).

Fixes runlevel concurrency issue

---

hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java

Removed redundant synchronization.
This could result in using incompletely initialized `ServiceLocator`.

Fixes race condition in `ServiceLocatorImpl`

---

class-model/pom.xml
pom.xml

Updates `osgi.enterprise` to 7.0.0.
Related PR to master branch: https://github.com/eclipse-ee4j/glassfish-hk2/pull/976

Update OSGi Enterprise to 7.0.0

---

osgi/adapter-tests/osgi-adapter-test/pom.xml
pom.xml

These managed dependencies seem to be used only in
https://github.com/eclipse-ee4j/glassfish-hk2/blob/8ed1807b41a7e46e8aa251e6c2913ef689bec63a/osgi/adapter-tests/osgi-adapter-test/pom.xml#L183-L190
But the `osgi-adapter-test` module was removed from the build anyway https://github.com/eclipse-ee4j/glassfish-hk2/blob/8ed1807b41a7e46e8aa251e6c2913ef689bec63a/osgi/adapter-tests/pom.xml#L38
- via #501 / 2b815f6a44a10e0fe63a005d4a4760d9228c75b5
Even if `osgi-adapter-test` was included - I could not see `logback` to transit in other version from anything there.
IF re-including `osgi-adapter-test` in the build would require `logback` - we could have it back again then.
-----
- Closes #992
- Closes #993

Drop `logback` dependencies

---

hk2-extras/pom.xml

Adds exports to the HK2-Extras module.
The subtle change to the bundle plugin config applied in https://github.com/eclipse-ee4j/glassfish-hk2/pull/899 which fixed the global config by making it no longer ignore the instruction to not export anything means that without an override this module doesn't export anything. I'd argue it should be exporting stuff, as things can depend on it.
I've limited the exports to anything not in an "internal" package.

Add OSGi Exports to HK2-Extras

---

bom/pom.xml
osgi/adapter-tests/osgi-adapter-test/pom.xml
osgi/adapter-tests/osgi-adapter-test/src/test/java/org/jvnet/hk2/osgiadapter/OSGiTest.java
osgi/adapter-tests/osgi-adapter-test/src/test/java/org/jvnet/hk2/osgiadapter/ServiceLocatorHk2MainTest.java
osgi/adapter-tests/pom.xml
pom.xml

Fixed several issues in these tests:
* Dependencies; PAX still uses javax packages (`@Inject`)
* Test detected wrong osgi-resource-locator version
* One test probably reproduces an issue, unfortunately we don't have access to the java.net any more. The test was marked as ignored.
* PAX Logging simply doesn't work, the only solution I have found is to stay with the latest working version.

Fixed osgi-adapter-test module

---

hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java

Fix for https://github.com/eclipse-ee4j/glassfish/issues/25467.
If the scope was not present in the current service locator, it threw an exception even if the scope was present in the parent. Now we first look for the scope in the parent locator, and if not found, we search in the current one.

Search for scope first in parent locator

---

Jenkinsfile

This one took
I propose the increase, as IMO it's better to have green Jenkins build rather than timout-related. I'd prefer to see failures for the code-related reasons.

Increase global timeout

---

hk2-api/src/main/java/org/glassfish/hk2/internal/InheritableThreadContext.java
hk2-core/src/main/java/com/sun/enterprise/module/impl/ClassLoaderFacade.java
hk2-core/src/main/java/com/sun/enterprise/module/impl/ClassLoaderProxy.java

Do not hold the `this` reference in the cleaning actions.

Fixes memory leaks in the `InheritableThreadContext` and classloaders
